apiVersion: v1
kind: Service
metadata:
        name: phpapp-service
spec:
        type: NodePort
        ports:
              - targetPort: 80
                port: 80
                nodePort: 30008
               
        selector:
                app: php-deployment
                type: front-end
                       

